### PR TITLE
Error handling

### LINKED ISSUE #25: Unhandled exception, when entered a wrong city name
image

### LINKED ISSUE #26: Change handling of "User denied Geolocation" exception
image

When I deny the Share geolocation request, the app shows no information at all (after I close the alert window).
image

MB it would be a better option to show information for some default city (Berlin or smth else) in case the user geolocation is unknown?

### PR DESCRIPTION
**Pull request by catalinac3**
closes #26 closes #25 
- Change in bigObjects.js 9d and 9n to 09d and 09n, it wasn't getting the animated icon for drizzle
- Added an "if" to catch error "city not found" because it was not going directly to the catch, but stopping at not getting the temperature, reporting a weird message.
- Created function handleErrorGeo to handle user denied location, this funtion takes a random city and does a fetchData() by city. 
- Created array in bigObjects.js to hold city names

### CODE REVIEW

File: jsFiles/app.js [hunk 1]
```diff
@@ -60,6 +60,13 @@ function fetchData(apiUrl, searchCity = false) {
     // of an asynchronous operation and its resulting value.
     .then((data) => {
       console.log(data);
+      // this code reports that city wasn't found
+      // because with code 404, it doesn't go directly to catch
+      // and it breakes with not finding temp in data.main.
+      if (data.cod == 404) {
```
Comment (correttojs) [inline jsFiles/app.js]: FYI you can also check the status code before parsing the response object. This is the standard browser API to detect the HTTP response status code

https://developer.mozilla.org/en-US/docs/Web/API/Response/status

**Comment by correttojs** [comment]
all good to me, I just left a comment about an alternative way to detect the status code

File: jsFiles/design.js [hunk 2]
```diff
@@ -35,51 +35,51 @@ function skyColor(sunrise, sunset, offsetTime) {
...
     } else if (timeInMinutes < startSunset + (aroundSunset / 3) * 2) {
       cardBody.style.backgroundImage = skyColors[9];
-      console.log("color 9 is on ");
+      //console.log("color 9 is on ");
     }
     // end section with color: black;  & filer: none
   } else if (timeInMinutes < endSunset) {
     cardBody.style.backgroundImage = skyColors[10];
-    console.log("color 10 is on ");
+    //console.log("color 10 is on ");
```
Comment (MrTim) [inline jsFiles/design.js]: so many console.logs :)

File: jsFiles/utility.js [hunk 3]
```diff
@@ -86,7 +86,21 @@ function formatTime(date, timeZone = undefined) {
...
 
 /**
- * handles the alert error messages of fetchData() and geolocation.getCurrentPosition()
+ * handles the alert error of geolocation.getCurrentPosition()
+ * @param {object} error - contains information about the error
+ */
+function handleErrorGeo(error) {
+  if (error.code == 1) {
+    const randomCity = cities[Math.floor(Math.random() * cities.length)];
+    const api = `${apiRootUrl}weather?q=${randomCity}&appid=${KEY}&units=metric`;
```
Comment (MrTim) [inline jsFiles/utility.js:95]: Hm...I'm not sure that it's a good idea to have a side effect inside your errorHandler. 
In general I'll propose to have this fetch data outside of the errorHandler and this function should deal only with what related to the error itself (displaying properly in most of the times).

**Review by MrTim — APPROVED** [review]
All good for me!
But left a comment about general improvement for `handleErrorGeo` function

File: jsFiles/design.js (hunk 2 above)
Comment (catalinac3) [reply jsFiles/design.js]: that is true, I will take them off

File: jsFiles/utility.js (hunk 3 above)
Comment (catalinac3) [reply jsFiles/utility.js:95]: I'm not sure if I understand, I thought this would be the place, since in case of an error (user denying the location) the weather of a random city is to show up instead. The function does deal with error handling otherwise the app well doesn't get any weather's data, like pointed out on the pic of Maria, on this pull request addressed comment. If I were to place this outside this function, then it would execute, and overwrite the fetch from the user location...

File: jsFiles/app.js (hunk 1 above)
Comment (catalinac3) [reply jsFiles/app.js]: It is now using response.status
